import { NextResponse } from 'next/server';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const UPLOAD_DIR = process.env.UPLOAD_DIR || path.join(process.cwd(), 'data', 'uploads');

// Only names generated by /api/upload: 32 hex chars + one known extension.
const SAFE_NAME = /^[a-f0-9]{32}\.[a-z0-9]+$/;

/**
 * GET /api/files/[name] — serve an image previously saved by /api/upload.
 * Serves from <cwd>/data/uploads (gitignored) so no external host is needed.
 */
export async function GET(_req, { params }) {
  const { name } = await params;
  if (typeof name !== 'string' || !SAFE_NAME.test(name)) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }
  const filePath = path.join(UPLOAD_DIR, name);

  let buffer;
  try {
    buffer = await readFile(filePath);
  } catch {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }

  const ext = path.extname(name).slice(1);
  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      'Content-Type': `image/${ext === 'jpg' ? 'jpeg' : ext}`,
      'Content-Length': String(buffer.length),
      'Cache-Control': 'public, max-age=31536000, immutable',
    },
  });
}